### ISSUE TITLE
Add a simple converter in the toolbar

### ISSUE THREAD

**Issue by privat** [rarsm/rars#25]
The toolbar can hold a simple integer converter for bin/hex/dec/ascii ; when a field is modified, the 3 others are updated

here is a mockup :

![Capture d’écran du 2024-06-28 14-29-42](https://github.com/privat/rars/assets/135828/5e0286c6-d1e0-43a3-99a9-89aceba5d7ca)

**Comment by ElTitoDG** [comment]
Testing to do this

**Comment by ElTitoDG** [comment]
I just implemented and extra button where it ask for the decimal number and converts to the other 3 formats

**Comment by ElTitoDG** [comment]
This is completed and should be closed

**Comment by privat** [comment]
closed by #83

**Comment by DvvCz** [comment]
I see the use for this, but it feels confusing. When I first saw it, I had no idea what it was for. It also takes up a pretty big amount of space in the menu which is otherwise pretty small.

Would the usecase for this be so common you need to constantly type numbers into this? Maybe instead tooltips could be added to every number that displays the value in hex/binary/ascii? And for the rare case you want to manually input a number, this should be in the tools section with everything else?
